### ISSUE TITLE
Build of project works on native windows and mac targets but fails on html5 target.

### ISSUE THREAD

**Issue by dimumurray** [openfl/svg#15]
I'm getting the following errors whenever I attempt to build the html5 target via lime.
> .../format/gfx/GfxBytes.hx:249: characters 38-53 : flash.display.CapsStyle should be EnumValue
> .../format/gfx/GfxBytes.hx:249: characters 38-53 : For function argument 'e'
> .../format/gfx/GfxBytes.hx:250: characters 38-54 : flash.display.JointStyle should be EnumValue
> .../format/gfx/GfxBytes.hx:250: characters 38-54 : For function argument 'e'

I got it to work (sort of) by editing GfxBytes.hx and commenting out lines 249 and 250. However, all my open path segments were rendered as closed paths. In addition, the stroke was at full opacity where I had it at around 50%. 

Here's the SVG file I tried to load with the svg library:
[map_00_optimized.svg]

[map_00_optimized.svg]:https://docs.google.com/file/d/0B5WA_i677AP6MmRCMUZfRl9OdTQ/edit

**Comment by jgranick** [comment]
Compiling on latest libraries
