### ISSUE TITLE
Code Reviewer

### ISSUE THREAD

**Issue by ashes999** [openfl/svg#43]
@openfl/svg-contributors  @openfl/lime-contributors @openfl/svg-contributors

We have a couple of PRs in the queue; one is about two weeks old (and aging). We really need someone with experience in the code-base to vet these, and/or merge them.

Is anyone interested in doing this, who has experience working with the SVG code-base?

Is anyone interested in doing this, who doesn't have much experience, but is willing to learn?

**Comment by ibilon** [comment]
I can help, not that familiar with the codebase but it's small enough, I'll dive into it.

I actually have tabs open with the pull requests, wanted to look at them, time goes by so quickly :)

**Comment by ashes999** [comment]
@ibilon thanks, I really appreciate it. 

I would suggest putting aside some small amount of time (maybe an hour a week or so). We don't need PRs merged urgently, just "eventually."

**Comment by ashes999** [comment]
@ibilon I've tagged you in all the reviews that need you to look at them (currently three PRs).
