### ISSUE TITLE
On static platforms, null can't be used as basic type Float

### ISSUE THREAD

**Issue by DropsOfSerenity** [openfl/svg#50]
Flash target fails to build on svg 1.1.0 but succeeds on 1.0.9

![image](https://cloud.githubusercontent.com/assets/2287977/19181994/717e2164-8c25-11e6-93bc-091b9ea71868.png)

**Comment by ibilon** [comment]
Is fixed on git version https://github.com/openfl/svg/commit/9205e3d83fa4241cb6b92f2c0aab8d5834861f86

@jgranick could we get a haxelib update?

**Comment by ashes999** [comment]
Looks like we have an update: 1.1.1
