### ISSUE TITLE
Import "flash." ?

### ISSUE THREAD

**Issue by madneon** [openfl/svg#57]
Sources use `import flash.[...]`, shouldn't it be `import openfl.[...]` already? Can I create pull request for this?

**Comment by jgranick** [comment]
By importing `flash.*`, I believe this library will work with the Haxe/Flash target directly, without the use of OpenFL, or will work in OpenFL, too.

However, this may not be important, and that it's hosted officially by OpenFL, we could consider this change (and then standard Flash users could add a --remap openfl:flash if desired)

**Comment by askmeaboutlo0m** [comment]
+1 this actually causes compilation to fail for me, telling me that I can't access the package `flash` when inside a macro. Replacing all occurrences with `openfl` makes it work correctly.
