### ISSUE TITLE
It loads all black?

### ISSUE THREAD

**Issue by Arthur-W-White** [openfl/svg#59]
[present.txt](https://github.com/openfl/svg/files/1077395/present.txt)

Rename the extension to 'svg' and test this file?
Not sure if I'm using the lib incorrectly but this loads as black on my office pc.
Thanks.

**Comment by ashes999** [comment]
I wonder if it's because you used the `<style>` tag in your SVG. I don't know if that's supported.

What tool did you use to make this SVG?

**Comment by Arthur-W-White** [comment]
I found out it's a "known issue".
tl;dr If you're exporting from Adobe Ilustrator, you need to select Style Attributes instead of (possibly the default) Style Elements. Thanks and good day. :)
Here is the solution's origin:
[robot paint issue 275](https://github.com/evil-mad/robopaint/issues/275)
