### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by CapnAndy** [openfl/svg#7]
Can you write up a usage example for this? I can't seem to write to the .graphics property of my sprites.

**Comment by ashes999** [comment]
I know this is a few years too late, but here goes: there's some code [here, in the tests](https://github.com/openfl/svg/blob/master/test/SvgGenerationTest.hx#L144-L152) that renders an SVG onto a BitmapData (and later, saves it to a `.png` file).

If this is not what you're looking for, and you're interested in this, please re-open this issue.
